#ifndef CACTO_COLLISIONS_EXPORT_HPP
#define CACTO_COLLISIONS_EXPORT_HPP

#include <Cacto/Config.hpp>

#ifdef CACTO_COLLISIONS_EXPORTS
#define CACTO_COLLISIONS_API CACTO_API_EXPORT
#else
#define CACTO_COLLISIONS_API CACTO_API_IMPORT
#endif

#endif