#define CACTO_GRAPHICS_EXPORTS
#include "Cacto/Graphics/DrawNode.cpp"
#include "Cacto/Graphics/Line.cpp"
#include "Cacto/Graphics/LineViewer.cpp"
#include "Cacto/Graphics/Straight.cpp"
#include "Cacto/Graphics/Bezier.cpp"
#include "Cacto/Graphics/Geometry.cpp"
#include "Cacto/Graphics/Rectangle.cpp"
#include "Cacto/Graphics/Ellipse.cpp"
#include "Cacto/Graphics/Triangle.cpp"
#include "Cacto/Graphics/Mesh.cpp"
// #include "Cacto/Graphics/Skeleton.cpp"
// #include "Cacto/Graphics/TileMap.cpp"
#include "Cacto/Graphics/ImagePack.cpp"
#include "Cacto/Graphics/TexturePack.cpp"
#include "Cacto/Graphics/Utils.cpp"