#define CACTO_LANG_EXPORTS
#include "Cacto/Lang/Printer.cpp"
#include "Cacto/Lang/Printable.cpp"
#include "Cacto/Lang/Scanner.cpp"
#include "Cacto/Lang/Scannable.cpp"
#include "Cacto/Lang/JsonValue.cpp"
#include "Cacto/Lang/JsonPrinter.cpp"
#include "Cacto/Lang/JsonScanner.cpp"
#include "Cacto/Lang/XmlValue.cpp"
#include "Cacto/Lang/XmlPrinter.cpp"
// #include "Cacto/Lang/XmlScanner.cpp"
#include "Cacto/Lang/StringUtils.cpp"